name: Hash Validator

on:
  push:
    branches:
      - main
    paths:
      - 'airyblocks/**/*.airyb'  # Only trigger on changes to .airyb files

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Validate No Tampering
        run: |
          # Compare only airyblocks/ .airyb files
          git fetch origin main
          git diff --name-status origin/main HEAD | grep -E '^M|^D' | grep 'airyblocks/.*\.airyb' && {
            echo "Error: Modifying or deleting .airyb files is not allowed.";
            exit 1;
          } || echo "Validation passed — no tampering with airyblocks/*.airyb."
