name: block-mutations

on:
  push:
    branches:
      - main
    paths:
      - 'airyblocks/**/*.airyb'

jobs:
  prevent-edits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to compare against history

      - name: Detect modified airyblocks
        id: check
        run: |
          git fetch origin main
          git diff --name-status origin/main | grep "^M\s\+airyblocks/.*\.airyb" && exit 1 || exit 0
