name: Prevent airyblock mutations

on:
  push:
    paths:
      - 'airyblocks/*.airyb'

jobs:
  enforce-immutability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect mutations
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-status origin/main HEAD -- 'airyblocks/*.airyb')
          echo "Changed airyblock files:"
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -qE '^[MDR]'; then
            echo "::error ::IMMUTABILITY BREACHED: airyblocks can only be added, not modified or deleted."
            exit 1
          fi
