name: Tamper Check Bot

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'

jobs:
  tamper-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run tamper bot
        run: node tamper/tamper_bot_v0.1.js

